version: '3.3'

services:

  backend:
    build: ./backend_test/
    ports:
      - 5000:5000
    volumes:
      - ./backend_test:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080